spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/book_management
    username: root
    password: password
  flyway:
    driver-class-name: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: validate

book-management-config:
  auth:
    password: superSecretPass    # Don't do this on production
  mock-string: Hello Kotlin!
